import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Navigation } from "./_components/navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
        <body>
          <div className="flex min-h-screen flex-col bg-[#0d1117]">
            <div className="gradient-bg fixed inset-0 -z-10 opacity-50" />
            <Navigation />
            <main className="flex flex-1">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
